[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "venny4py"
version = "0.1.1"

description = "venn4py"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "matplotlib",
]

[tool.poetry.classifiers]
programming-language = "Python :: 3"
license = "OSI Approved :: MIT License"
operating-system = "OS Independent"
