[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "venny4py"
version = "0.1.1"

description = "venn4py"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "matplotlib",
]


[tool.hatch.build.targets.wheel]
packages = ["venny4py"]